# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2519e15b6b7a00cf92a39ece4c9803066ef748d3bca7813ea76a15c20d07b60b32066639112943083313a0c020d8048f54aa89cb80774c81cdbb50cf6fd37a90

test:
  secret_key_base: 4e59f1b8ecd7e1fd18a32181797565ba3c71aef199358448ffd112e62fc7edf46cff620d4f9539bb5ca7c3b34fbe287c5b660d3fd2d2ddebf49e58150a1a530e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
